### ISSUE TITLE
[CMS Tracker] Missing language changed and other GitHub Labels

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#1068]
#### Steps to reproduce the issue

Please check this CMS PR for example: https://github.com/joomla/joomla-cms/pull/27190 it changes an language file but it is missing the language changed label. It also seams that PR* labels are not done by the bot anymore. Is / was this an intended change?

**Comment by mbabker** [comment]
Probably related to https://github.com/joomla/jissues/commit/570aa6b2a28be31b43055bd41f7d8e19ba86f1e1 but I'm not about to revert all of the "use Framework 2.0" stuff.

Someone check to see if the webhooks are sending non-200 responses through the admin interface on the CMS repo to see if there are any errors being returned.  There's nothing useful in the app logs pointing to errors so I imagine it actually has to do with the (too dynamic) event listener registration.

Otherwise, I might find time later this week to look into it more.

**Comment by mbabker** [comment]
Or maybe https://github.com/joomla/jissues/commit/570aa6b2a28be31b43055bd41f7d8e19ba86f1e1 fixed it.

**Comment by mbabker** [comment]
Or maybe https://github.com/joomla/jissues/commit/11a8deed958db4ef3d51a347fab36570f96c15e2 fixed it.

**Comment by zero-24** [comment]
lgtm https://github.com/joomla/joomla-cms/pull/27197 the bot seams to be active again.

The webooks are green but the response was: `string(17) "pull after update"` this is fixed now. Thanks @mbabker
