### ISSUE TITLE
404 for markdown route

### ISSUE THREAD

**Issue by ot2sen** [joomla/jissues#1069]
When clicking the 'Markdown Help' at top/right above the comments area you get a 404 Joomla\Router\Exception\RouteNotFoundException
Unable to handle request for route `markdown`.

*wasn´t able to add/upload the screenshot taken. Visit the URL instead https://issues.joomla.org/markdown

**Comment by mbabker** [comment]
On the image upload thing, check for any console errors please (the JavaScript library got updated recently because of a security warning, it's entirely possible something got broken along the way).

The markdown page being gone is intentional (https://github.com/joomla/jissues/commit/8082b2b0bfbcb7ee46e8362232320d7c460d6592), I guess I need to find links to it and point them to GitHub instead.

**Comment by ot2sen** [comment]
The console gives these two errors:

SCRIPT438: SCRIPT438: Object doesn't support property or method 'scale'
blueimp-file-upload.js (1,31499)

HTTP404: IKKE FUNDET - Serveren har ikke fundet noget, der svarer til den ønskede URI (Uniform Resource Identifier).
GET - https://issues.joomla.org/media/css/img/loading.gif
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/1069">issues.joomla.org/tracker/jtracker/1069</a>.</sub>
