### ISSUE TITLE
Establish git workflow for release/deploy

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#505]
It's going to be impractical to always depend on someone to synchronize the live website with the git repository master branch or to automate deployments to the live environment.  Prior to officially tagging a 1.0.0 stable release, we should establish a workflow with regards to how patches will be merged between tags (releases), how architectural changes will be handled (files will work OK when checking out git tags or revisions, but database schema updates will need some thinking), and how languages will be managed for releases.  Any other concerns should be addressed within this issue too.

**Comment by allenzhao** [comment]
About SQL or DB versioning, since I've started to work with Rails recently, I think we can implement a db migration module (or maybe there is already a similar solution like [dbv](http://dbv.vizuina.com/) ) which mangaes a db scheme file to log the whole db generate file(just like the sql file in /etc currently.
And everytime a change should be versioned to get every developer's working copy of JTracker working under the correct version of db and make deploy easier.

**Comment by mbabker** [comment]
This never caught priority anyway.
