### ISSUE TITLE
Bug in Issue Tracker

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#606]
#### Steps to reproduce the issue
Submitted Issue #5960 . Screen refreshes and I get as attached error![screen shot 2015-02-03 at 22 38 44](http://issues.joomla.org/uploads/1/38bba7b9051060a473804b9e910351ff.jpg)

#### Additional comments
see: https://github.com/joomla/joomla-cms/issues/5961 by @gwsdesk

**Comment by brianteeman** [comment]
I got the same thing creating an issue here - although the issue was actually created<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/606">issues.joomla.org/jtracker/606</a>.</sub>

**Comment by b2z** [comment]
Looks like some kind of DB problem. Not sure.

BTW we have a security flow here - since we are public we should not throw an exception to user... My proposal is to log any Exception errors and show some friendly message to user like "An error has occurred. Please report it to https://github.com/joomla/jissues/."

**Comment by mbabker** [comment]
I rolled back the filter package again.  Apparently something after 1.1.2 is screwing things up royally.

**Comment by mbabker** [comment]
My issue on the last two test items I posted, you can't select `No Milestone` (if you have that option in the sidebar).

**Comment by b2z** [comment]
>  you can't select No Milestone

What do you mean? It is the default value.

BTW that i s the same error that was in #579 and was fixed in a3aa0eae. It seems that it was not? :)

**Comment by mbabker** [comment]
I can't submit the item with No Milestone as the selected value.  If I change it to a value which has an ID in the milestones table, it works.  The 0 is killing it.

**Comment by elkuku** [comment]
We should have placed the code @wilsonge submitted in #581 in the table class as @b2z [commented](https://github.com/joomla/jissues/pull/581#issuecomment-67730127)...
