### ISSUE TITLE
Does the bot still work properly?

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#647]
see: http://issues.joomla.org/tracker/joomla-cms/6868 & https://github.com/joomla/joomla-cms/pull/6868
 
This is a PR but we need manually move it to pending and add the labels. Or does the bot need only some more time now?

Yesterday i need to add some missing labels and i moved also some issues manually to pending. So I'm not sure where the issue is ;)

**Comment by b2z** [comment]
What the heck? :)

**Comment by zero-24** [comment]
hmm looks like we run into a issue here? (Regarding the issue message) Maybe we can debug there?

https://github.com/joomla/jissues/blob/master/src/JTracker/Database/AbstractDatabaseTable.php#L312

**Comment by mbabker** [comment]
OK anything that throws an exception and makes it up to the Application class now logs the exception (available to admins in the logs menu).  That should start to help some at least for this error.

I also registered a logger into the DatabaseDriver now, it should log any errors that come from the database (database log in the menu).

So that should help some with things in general.  I still need to deal with catching output from the cron jobs to collect error data.

**Comment by b2z** [comment]
http://issues.joomla.org/logs/database - @todo prettifyMe ;)

**Comment by mbabker** [comment]
An empty log is a good log :wink:

**Comment by b2z** [comment]
Ok I think I found where the problem is. Will try to PR in few days :wink:

**Comment by zero-24** [comment]
Great! :+1:  That will save a lot of hours :smile:
