### ISSUE TITLE
Remove Test Instructions Label if instructions are added

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#690]
As a companion for #687 the label should be removed when the description gets filled in.

// @zero-24

**Comment by zero-24** [comment]
Technical no Problem. But than we need to run that check also on every comment and if the creator adds a description and a comment the label gets removed. If that is deliberately i can prepare a pull.

**Comment by mbabker** [comment]
It shouldn't be needed to listen for that in the comment listener webhook as the only way you can get that condition is using the tracker's UI (which doesn't let you save an empty description anyway IIRC).  GitHub should be sending a separate update event if you change the description (and if they don't the update would get picked up with the cron jobs).

**Comment by zero-24** [comment]
ok so we need to add that check to the cron job ;)

I'm correct here?: https://github.com/joomla/jissues/blob/master/cli/Application/Command/Get/Project/Issues.php#L253-L267

**Comment by mbabker** [comment]
I wouldn't worry about it right now since none of the listener checks are being done in the cron jobs right now.

**Comment by zero-24** [comment]
On coding i just run into a logical issue.

If the bot add the label and the submiter add instructuions the label should be removed if there is any kind of text / description.

But if a CMS Maintainer adds the label it should not get removed. The Problem is we can't check with code if the reasons was missing text (no text at all) or any other.

So i think we have two options:
1. New Label
- add a label like `description missing` (the bot one)
- let the actual label be handeld as currently.

2. Don't do it automatic by the bot let a human decide if it gets removed or not.

**Comment by mbabker** [comment]
Closing, let it be done manually.  Unless we're planning on replacing everyone with bots, there's still points where a human has to take action.
