### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by wilsonge** [joomla/jissues#720]
![image](https://cloud.githubusercontent.com/assets/1986000/10711522/dc0dc984-7a75-11e5-8e9d-eae008f64c30.png)
Issue with responsive view on iPhone 6S. There aren't any obvious elements sticking out into the white space. So not sure what the issue is.

**Comment by mbabker** [comment]
I'm not sure what I'm supposed to be looking at?  Other than already knowing the layouts are ugly as sin on a non-desktop layout.

**Comment by wilsonge** [comment]
All the grey space on the right hand side of the image

**Comment by wilsonge** [comment]
The actual content is only in left 1/2 - 3/4 of the screen

**Comment by Sandra97** [comment]
Can't reproduce this issue. What's the screen resolution of your tablet?

**Comment by wilsonge** [comment]
It's just a standard iPhone 6S

**Comment by mbabker** [comment]
On that single page I can see it but in general it's not an issue aside from standard lack of responsiveness in a lot of places.

**Comment by b2z** [comment]
We need BS3 theme :tongue: and/or huge help of UI experts.

**Comment by wilsonge** [comment]
@crystalenka *cough*

**Comment by crystalenka** [comment]
I can't reproduce it on my computer or on my inside an individual issue, but on the list view everything breaks.

![screenshot](https://cloud.githubusercontent.com/assets/9141288/10765529/9281d36a-7ca9-11e5-8dbb-202e5845d01d.PNG)

Possibly a different issue, but since I can't reproduce the original issue, maybe they're related.

**Comment by zero-24** [comment]
Known issue see: https://github.com/joomla/jissues/issues/717

**Comment by mbabker** [comment]
I keep saying the mobile layouts are garbage.  This is why you don't let developers design.

**Comment by mbabker** [comment]
But maybe something fixed itself on that issue since George reported it, but http://issues.joomla.org/tracker/joomla-cms/8024 on my iPhone definitely duplicated his original screenshot (downsizing the browser didn't accomplish it; I had to load the page with Chrome's emulator turned on to get it to do anything).

**Comment by crystalenka** [comment]
I just emulated iPhone 4- iPhone 6S and none of them reproduced the issue. Possibly was a safari issue that Apple fixed?

**Comment by b2z** [comment]
So? Closing it?
