### ISSUE TITLE
hamburgermenu issuetracker not working in firefoxmobile

### ISSUE THREAD

**Issue by Klipper** [joomla/jissues#740]
#### Steps to reproduce the issue
Open the issuetracker in Firefox mobile(latest) on Android, or default 'Internet' browser (Samsung)
Push the hamburgermenu button.
The menu appears.
Try one of the menu-items: Nothing happens, except that the menu disappear again. 

#### Expected result
Navigate to the chosen menu-item

#### Actual result
Menu disappear, but no navigation to the chosen menu-item.

#### System information (as much as possible)
Latest Firefox 43.0 mobile on Android 4.4

**Comment by b2z** [comment]
Actually our theme should be totally revamped, because there is a lot of such little issues that should be fixed. But unfortunately I do not think that it is possible in current version of JTracker that is based on old Bootstrap :(

If someone will make a new modern theme... Sometimes...

**Comment by mbabker** [comment]
Some of the stuff with the global `joomla.org` template is because we're using native Bootstrap and not the CMS' hacked version, and this is especially evident in the mega menu.  As for our internal content, given there's a team supposedly working on a new template, I wouldn't invest too much time into major UI work until that gets shared.
