### ISSUE TITLE
Recent template change?

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#765]
#### Steps to reproduce the issue
Try any of the dropdown select boxes in the search tools - they are hidden below the content - see screenshot

![screen shot 2016-03-22 at 09 35 59](https://issues.joomla.org/uploads/2/640d38223f79b381d58814d1abc21fe3.png)

**Comment by brianteeman** [comment]
It is only the dropdowns with the class bootstrap-select<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/765">issues.joomla.org/jtracker/765</a>.</sub>

**Comment by mbabker** [comment]
Looking back we've had a lot of issues with that package (and we're now a bunch of releases behind).

**Comment by mbabker** [comment]
I went back before the asset restructure and took a look.  On the tracker list page, we were never loading bootstrap-select so all the filters were "plain" `<select>` lists.  With the compiled assets it's always loaded in now in the `vendor.min.*` files.  Putting the template in debug mode still doesn't load bootstrap-select since it was never a declared dependency of this page.

Long and short, gotta deal with it now.

**Comment by mbabker** [comment]
Found the conflict.  The fact that search tools is in a collapse container caused the overflow to be hidden.  So we need to show the overflow when that container is expanded.

I also updated to the latest bootstrap-select version (1.10.0).  So this should be OK for now.

**Comment by zero-24** [comment]
Maybe somone with access can test if that issue is fixed with that change too :)

https://github.com/joomla/jissues/issues/640

**Comment by mbabker** [comment]
The text when hovered over shows fine, the input box overflow is still an issue.
