### ISSUE TITLE
Error displaying the error page: Application Instantiation Error: Failed to start the session

### ISSUE THREAD

**Issue by ninad1987** [joomla/jissues#779]
#### Steps to reproduce the issue

PHP 7 Joomla 3.5.0
Start the joomla installation

#### Expected result
Joomla Installation Begin

#### Actual result
Error displaying the error page: Application Instantiation Error: Failed to start the session

#### System information (as much as possible)
PHP 7 Joomla 3.5.0

#### Additional comments
Researched all over the forum but no luck for solution.

**Comment by mbabker** [comment]
This issue tracker is for issues with the Joomla issue tracker.

For bugs with the Joomla CMS please use https://github.com/joomla/joomla-cms
For user support issues (such as this) please use http://forum.joomla.org

**Comment by ninad1987** [comment]
This is not a user support issue. This is a joomla bug.

**Comment by ninad1987** [comment]
Joomla 3.5 is not compatible with PHP 7.

**Comment by mbabker** [comment]
Yes it is, I did the work myself to make it compatible and I've deployed a few sites onto PHP 7 since 3.5's release.  The fact that you're getting an error relating to session startup indicates an issue with your hosting environment.  This could range anywhere from failing to connect to the session handler's storage to some code spitting output or sending response headers before the session is started (which PHP does not allow).  In either case, post on the forums and folks will assist you there as they are able.  If a consistently reproducible core bug is found, then submit a bug report with all of that data.
