### ISSUE TITLE
I can not change or delete my account (myself) on issues.joomla.org 

### ISSUE THREAD

**Issue by xgoon** [joomla/jissues#791]
https://issues.joomla.org/user/66
How can i change my Name? if not, please remove my account on your system?

Regards

**Comment by elkuku** [comment]
You can change your name only on GitHub.
The data in issues.joomla.org is only imported once. If you change your profile information afterwards (on GitHub), please visit your profile page (the link you posted) and find a button named `Refresh profile from GitHub`.
Does that solve your issue?

**Comment by mbabker** [comment]
I went into the database and manually corrected the name.

As noted, in the future you'll need to log in and hit the "Refresh profile from GitHub" button which refreshes your name, username, and e-mail address based on your GitHub profile (these are the only fields which we store).

Also for reference, we don't actually have "accounts" on the `issues.joomla.org` domain beyond your authorization for our application to use OAuth to log into the site, and that's managed with GitHub itself.  Because we are synchronizing issue data with GitHub, we store this user data (name, username, and e-mail address which come from your GitHub profile and accessible via GitHub's REST API) in our users table to be able to properly cross reference records and activities on the site.
