### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#797]
Menu doesn't work on mobile devices

#### Steps to reproduce the issue

Try to use the joomla menu to visit the community site

#### Expected result
Link works as it does in other joomla.org sites

#### Actual result
Link does nothing

#### System information (as much as possible)
Tested with android on Xperia z3 phone and Nexus 7 tablet

**Comment by mbabker** [comment]
It's a difference between the Joomla "hacked" Bootstrap and using the unaltered product (same issue exists on the API site).

**Comment by mbabker** [comment]
I'm borderline tempted to close this as won't fix.  As I said, it's a behavioral difference between the Joomla "hacked" Bootstrap and the "pure" version and I have the same issue with the API site (all HTML documents).  If you want to pull down the API site's index.html file and see if there's something that can be changed to make it work at that level we could probably fix it, otherwise it's either we change how Bootstrap gets pulled in for those two sites or leave it alone.

Note this is just one of the little behavioral differences.  Another obvious one is the "rollover" effect on the mega menu (CMS' version supports it, native Bootstrap doesn't).

**Comment by b2z** [comment]
Agree to close. There is no much we can do about it, unless CSS experts will step in ;)

**Comment by brianteeman** [comment]
Wouldnt it be better to keep it open so that if someone with the css skills
comes on board they can see the issue that needs fixing

On 21 June 2016 at 09:17, Dmitry Rekun <notifications@github.com> wrote:

> Agree to close. There is no much we can do about it, unless CSS experts
> will step in ;)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/jissues/issues/797#issuecomment-227371874>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABPH8bRFjF2dH5fG_9GJDcZDFDXVoUJgks5qN54qgaJpZM4I4o7q>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
It's not CSS.  It's 100% JavaScript.  The way that Joomla altered the Bootstrap JavaScript API causes the behavioral differences.

I built the help.joomla.org offline page using the Joomla altered version of Bootstrap and the mega menu functions correctly there.  AFAIK there isn't a way to extend the needed plugins of Bootstrap to add those changes, so the only option is to go with the core hack, specifically I believe it's [this hack](https://github.com/joomla/joomla-cms/blob/staging/media/jui/js/bootstrap.js#L722-L734) in the Dropdown plugin.

**Comment by mbabker** [comment]
Moved to websites repo, see https://github.com/joomla/joomla-websites/issues/569

**Comment by brianteeman** [comment]
Thanks
