### ISSUE TITLE
Language Module Hover 

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#804]
When you hover over the local native language name you always see the english languages name displayed and not the native name for that locations

Example 
Nederlands has the hover Dutch no matter what language you are using the tracker in 
If you were using the tracker en français then it should be néerlandais

**Comment by elkuku** [comment]
Not sure what to do here.
The purpose of using english for the `alt` and `title` tag was somewhat of a "debugging helper"...
I am aware that it isn't a proper usage for a `title` or `alt` tag (or *is* it? since `alt` means "alternate"...).
en-GB is also used always as a "fall back", when no translation exists.

It would be cool to have every language translated to any language we use, but I am not sure that we should add 324 new language strings just for the language selector.

**Comment by brianteeman** [comment]
OK so I would either fall back to en-GB **IF** there is no localised translation OR I would **always** display the language code as the ALT instead

**Comment by elkuku** [comment]
What if we display the code along with the en-GB name like this:
![2016-06-23-121255_1366x768_scrot](https://cloud.githubusercontent.com/assets/33978/16312835/2f795c34-393c-11e6-9eb1-2c90f2d16bcb.png)
Would that make any sense?

**Comment by brianteeman** [comment]
Fr-fr makes sense globally as that is a standard. Would "French" have any
meaning to someone in China?

**Comment by elkuku** [comment]
OK so I'm gonna trust you on this one :wink:
