### ISSUE TITLE
Doc pages about t9n process need to be updated

### ISSUE THREAD

**Issue by MATsxm** [joomla/jissues#825]
JIssues Doc pages about l10n process need to be updated

- [ ] https://issues.joomla.org/documentation/view/?page=Dependencies&path=Development
- [x] https://issues.joomla.org/documentation/view/?page=Transifex&path=Internationalisation

#### Additional comments
Can be assigned to @MATsxm @Sandra97 & a dev for the technical part. :wink:

**Comment by mbabker** [comment]
All the docs live here in the repo, https://github.com/joomla/jissues/tree/master/Documentation

The tech part is easy.  I run a command on the server, the database is updated, everyone is happy.

**Comment by Sandra97** [comment]
For transifex.md, is it possible to rename it crowdin.md or is it better to create it?

**Comment by elkuku** [comment]
Please note the "improve" button present on every docs page :wink: 

Please create the `crowdin.md` page, since we still support Transifex in our code...

The "Dependencies" page is auto generated. The code lives [here](https://github.com/joomla/jissues/blob/master/credits.json#L42). There is also some native English speaker required to choose a proper wording :stuck_out_tongue_winking_eye: 

Thanks!

**Comment by elkuku** [comment]
Resolved by #827
