### ISSUE TITLE
Issues saving items via the tracker

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#834]
#### Steps to reproduce the issue

trying to change the category on 1120
(not just this one but its an example)
#### Actual result

0 UnexpectedValueException

No issue number received.

exception: exception 'UnexpectedValueException' with message 'No issue number received.' in ROOT/src/App/Tracker/Controller/Issue/Save.php:57
Stack trace:
#0 ROOT/src/JTracker/Application.php(170): App\Tracker\Controller\Issue\Save->execute()
#1 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#2 ROOT/www/index.php(97): Joomla\Application\AbstractWebApplication->execute()
#3 {main}

**Comment by elkuku** [comment]
This is one of those issues that really *sucks*....

I just "requested" a database dump to test with locally (#839).

Otherwise I only have the unhelpfully "can't reproduce" message...

Just to be sure: does it happen only when adding categories? The error message seems to indicate that it happens on every edit?

**Comment by elkuku** [comment]
Just a little update: Instead of solving the issue, I discovered more bugs along the way...

@brianteeman may I beg you for some more information? Does it only happen on 11120 or on which other issue(s)?

**Comment by brianteeman** [comment]
I have seen this on every pr that has been marked as closed on github.
(There is an issue for that)
This time it seemed specific to 11120. Not had it in any pr since and I
edit almost all of them and its not specific to me as @infograf768 had the
same issue on this one.

**Comment by elkuku** [comment]
TBH I'm a bit more confused now...
I tried to change the category on several closed PRs successfully, also 11120 is actually `open`.....

I can however confirm the bug on 11120 (and *only* on 11120), so yes, it's not specific to you :wink:

**Comment by brianteeman** [comment]
Weird. It definitely was not working as I've reported it twice

**Comment by elkuku** [comment]
Just a wild guess: Could the unfriendly behavior of mod_security reported in #850 be related to the issue we are facing here? The only thing I can really confirm is that something or someone is wiping out the request data **on the server**.
So the mod_security thingy would be the last explication I got left and if this can be confirmed I could finally sleep in peace (somewhat, because someone else has to solve it) :wink: 

I labeled them both as server issues.

**Comment by mbabker** [comment]
No idea, since the data gets stripped before it hits any place we can log it.

FWIW the GitHub hooks should fail less frequently again, I had the rules loosened up again.

**Comment by elkuku** [comment]
> FWIW the GitHub hooks should fail less frequently again, I had the rules loosened up again.

Glad to hear some good news in those days with logs full of strange errors...

**Comment by mbabker** [comment]
If it happens again someone say something, I've got logging in place to get the submitted data now.

**Comment by brianteeman** [comment]
I just made it happen right now on 11899

0 UnexpectedValueException

No issue number received.

exception: exception 'UnexpectedValueException' with message 'No issue number received.' in ROOT/src/App/Tracker/Controller/Issue/Save.php:61
Stack trace:
#0 ROOT/src/JTracker/Application.php(174): App\Tracker\Controller\Issue\Save->execute()
#1 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#2 ROOT/www/index.php(104): Joomla\Application\AbstractWebApplication->execute()
#3 {main}

**Comment by mbabker** [comment]
```sh
[2016-09-05 09:35:30] JTracker.DEBUG: Submitted data from save controller. {"data":[]} {"url":"/tracker/joomla-cms/11899/edit-save","http_method":"GET","server":"issues.joomla.org","referrer":"https://issues.joomla.org/tracker/joomla-cms/11899/edit","unique_id":"V82CskgdfJ4AADOldOYAAAAO"}
```

Have I mentioned lately how much I hate ModSec?

**Comment by mbabker** [comment]
Wait a second.  That says it was submitted with a GET request.  The page is set to submit the form via POST (side note the controller's not checking in POST for that data so that shouldn't make a huge difference I'd think).  Something with the JavaScript handlers messing that up somehow?

Either way I'm submitting a ticket to Rochen right now to see if anything's being stripped.  We'll see what happens.

**Comment by mbabker** [comment]
The save route should now be whitelisted on ModSec.
